Repository Samrudhipawar/whack-a-mole-game, pull requests merged in 2025-08, with the labels that each got.

#16 Added Diglett mole sprite + a popup animation
  Daco_5139344.png
  index.html
  whack-a-mole.css
  whack-a-mole.js
Labels: enhancement, good first issue, Level2, Gssoc 25, frontend

#33 added themes
  alien.png
  camel.png
  index.html
  octopus.png
  theme1bg.png
  theme1mole.png
  whack-a-mole.css
  whack-a-mole.js
Labels: enhancement, good first issue, Level2, frontend, GSSoC'25

#31 added feature : how to play Game
  index.html
  whack-a-mole.css
  whack-a-mole.js
Labels: enhancement, good first issue, Level2, frontend, GSSoC'25

#34 Feature Proposal: Add Navbar, Footer, and Pause Button to the Game #32 Completed
  about.html
  index.html
  whack-a-mole.css
  whack-a-mole.js
Labels: enhancement, good first issue, level 3, frontend, GSSoC'25
